server:
  host: localhost
  port: 8000
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
  read_timeout: 30
  write_timeout: 30
  max_header_bytes: 1048576

neo4j:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "password123"
  database: "neo4j"

weaviate:
  host: "98crrslth6p0jv5wzwiq.c0.asia-southeast1.gcp.weaviate.cloud"  # Replace with your actual cluster URL
  scheme: "https"
  class: "MathContent"
  api_key: "bTJHVTdjOUlaT0xRVXJ1QV9OZkJJRFo5T3N0a1VoaGFkeXJqOTZXK25yamZtS1ZUSnBELzFoRGJpaXNvPV92MjAw"

llm:
  provider: "gemini"
  api_key: "AIzaSyADe19Cxq_Yyq7RbHkPEeld0RdZ1fisMRw"
  model: "gemini-2.5-pro"
  temperature: 0.1
  max_tokens: 2000
  retry_attempts: 3

logging:
  level: "info"
  format: "json"