version: "3.8"

services:
  # Neo4j Knowledge Graph
  neo4j:
    image: neo4j:5.15
    container_name: mathprereq-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    volumes:
      - neo4j_data:/data
    networks:
      - mathprereq-network

  # MongoDB for Educational Resources
  mongodb:
    image: mongo:7.0
    container_name: mathprereq-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mathprereq
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mathprereq-network

volumes:
  neo4j_data:
  mongodb_data:

networks:
  mathprereq-network:
    driver: bridge
